config/routes.rb
Rails.application.routes.draw do
  resources :noids

  namespace :api, defaults: {format: :json} do
    resources :noid_list, only: [:index] do
      resources :noids, only: [:index, :create, :update, :destroy]
    end
  end

    namespace :api, defaults: {format: :json} do
      resources :noid_list, only: [:index] do
        resources :noids, only: [:index, :create, :update, :destroy]
        end
    end
  end

app/models/noid.rb
class Noid < ActiveRecord::Base
      belongs_to :prototype, :class_name => 'Noid', :foreign_key => "prototype_id"
      has_many   :instances, :class_name => 'Noid', :foreign_key => "prototype_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/noids_controller.rb
class NoidsController < ApplicationController
  before_action :set_noid, only: [:show, :edit, :update, :destroy]

  # GET /noids
  # GET /noids.json
  def index
    @noids = Noid.all
  end

  # GET /noids/1
  # GET /noids/1.json
  def show
  end

  # GET /noids/new
  def new
    @noid = Noid.new
  end

  # GET /noids/1/edit
  def edit
  end

  # POST /noids
  # POST /noids.json
  def create
    @noid = Noid.new(noid_params)

    respond_to do |format|
      if @noid.save
        format.html { redirect_to @noid, notice: 'Noid was successfully created.' }
        format.json { render :show, status: :created, location: @noid }
      else
        format.html { render :new }
        format.json { render json: @noid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noids/1
  # PATCH/PUT /noids/1.json
  def update
    respond_to do |format|
      if @noid.update(noid_params)
        format.html { redirect_to @noid, notice: 'Noid was successfully updated.' }
        format.json { render :show, status: :ok, location: @noid }
      else
        format.html { render :edit }
        format.json { render json: @noid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noids/1
  # DELETE /noids/1.json
  def destroy
    @noid.destroy
    respond_to do |format|
      format.html { redirect_to noids_url, notice: 'Noid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noid
      @noid = Noid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noid_params
      params.require(:noid).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/noids_helper.rb
module NoidsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<html ng-app="noidApps">
<head>
  <title>Noids</title>
  <%#= javascript_include_tag 'angular.min', 'data-turbolinks-track' => true %>
  why this line ? where else do we link to angualar script file?
  do you want separate palce for angular js work ?
  i don't understand
  i thought angular.min was a script that we should link to

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> <------     already link here
  this 'application' mean application.js
  <%= csrf_meta_tags %>
</head>
<body ng-controller="AppsController as apps">
<%= yield %>
</body>
</html>

app/views/noids/_form.html.erb
<%= form_for(@noid) do |f| %>
  <% if @noid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@noid.errors.count, "error") %> prohibited this noid from being saved:</h2>

      <ul>
      <% @noid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/noids/edit.html.erb
<h1>Editing noid</h1>

<%= render 'form' %>

<%= link_to 'Show', @noid %> |
<%= link_to 'Back', noids_path %>

app/views/noids/index.html.erb
<div class="noid row">
  <h3>
    {{"aha"}}
    {{apps.noid.name}}
    <em class="pull-right">{{apps.noid.country}}</em>
  </h3>
</div>


<div>
<h1>Listing noids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @noids.each do |noid| %>
      <tr>
        <td><%= noid.name %></td>
        <td><%= link_to 'Show', noid %></td>
        <td><%= link_to 'Edit', edit_noid_path(noid) %></td>
        <td><%= link_to 'Destroy', noid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Noid', new_noid_path %>

</div>

app/views/noids/new.html.erb
<h1>New noid</h1>

<%= render 'form' %>

<%= link_to 'Back', noids_path %>

app/views/noids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @noid.name %>
</p>

<%= link_to 'Edit', edit_noid_path(@noid) %> |
<%= link_to 'Back', noids_path %>

app/views/welcome/index.html.erb
<a href="" class="btn btn-default">Hello world</a>

<span class="glyphicon glyphicon-map-marker">Demo</span>

                                            <div class="clearfix"></div>
<!-- Split button -->
<div class="btn-group">
  <button type="button" class="btn btn-danger">Action</button>
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li class="divider"></li>
    <li><a href="#">Separated link</a></li>
  </ul>
</div>

<div class="clearfix"></div>
<div class="well well-sm">DemoDemo</div>